#!/usr/bin/env python3
import requests as req
from sys import argv
try:
    if len(argv[1]) > 0:
            help_c = argv
            if "-h" in help_c:
                print("python3 xssv.py <file name>")
            else:
                try:
                    target=argv[-1]
                    file = open(target,"r")
                    for i in file.readlines():

                        ready = i.replace("FUZZ","daiierfan")
                        read = str(ready)
                        # print(read)
                        try:
                            send = req.get(f"{read}")
                            answer = str(send.text)
                            if  "daiierfan" in answer:
                                print("pssible for xss -> "+i)
                        except:
                            pass
                        file.close()
                except:
                    pass



except:
    print("enter some valid file or -h")
